import { Badge } from '@/components/ui/badge';
import type { Tag } from '@/types/index';

interface TagBadgeProps {
  tag: Tag;
}

/**
 * Displays a tag as a small colored badge.
 *
 * The background and text color are derived from the tag's `color` (HEX).
 * We use inline styles because the color values are dynamic and cannot
 * be statically generated by Tailwind at build time.
 */
export default function TagBadge({ tag }: TagBadgeProps) {
  return (
    <Badge
      variant="secondary"
      style={{
        backgroundColor: `${tag.color}22`, // 13% opacity tint
        color: tag.color,
        borderColor: `${tag.color}44`,
      }}
      className="text-xs font-medium border"
    >
      {tag.name}
    </Badge>
  );
}
